### ISSUE TITLE
Configurable DNS server

### ISSUE THREAD

**Issue by kzyapkov** [mongoose-os-libs/ethernet#7]
On ESP32, when using ethernet, the DNS server being used is not really configurable. This library doesn't have a slot for it, and the DNS provided as a DHCP option is ignored.

It seems the deeper issue is that mongoose doesn't handle working with multiple network interfaces the way it should, but we should really be able to configure the DNS server being used for lookups.

A quick and easy solution may be to expose the global default (currently hardcoded to 8.8.8.8) as a config option.

**Comment by rojer** [comment]
I went further into the woods than strictkly necessary, but I wanted to improve this part anyway.
But now it's done, the following commits are relevant:

https://github.com/mongoose-os-libs/ethernet/commit/b7f158955341083d120d7f0fffce49e0838cd089
https://github.com/cesanta/mongoose-os/commit/c40286b17177ba5a5d7f94a7f37ec518a52b80cf
https://github.com/mongoose-os-libs/core/commit/9cbb8437919696a4a8779ebb4d0cd78d99890ac6
https://github.com/mongoose-os-libs/lwip/commit/1f2af44b9a4c074a82b5f76c46e5e299b892f5aa
https://github.com/mongoose-os-libs/wifi/commit/d5e5b6b7441e19978b4cca3356a6122535d57c0c
https://github.com/mongoose-os-libs/pppos/commit/7f0b3444405b104e1c7dbf490adde11176e49d87
https://github.com/mongoose-os-libs/wifi-ism43xxx/commit/9687aba1d6d0aa908c09bda1e778ef0191b61cc4

After these changes, mos will actively manage the DNS server used by mongoose, in particular it will use Ethernet if configured and up, then WiFi, then PPP. `eth.nameserver` will configure ethernet DNS in static mode.

I verified that fallback/fall forward between PPP, ethernet and wifi works as expected (on ESP32 at least).
